terms:
  - id: 1
    term: "Acquisition"
  - id: 2
    term: "Aptitude"
  - id: 3
    term: "Attrition"
  - id: 4
    term: "Autonomy"
  - id: 5
    term: "Bilingualism"
  - id: 6
    term: "Community or heritage languages"
  - id: 7
    term: "Complexity"
  - id: 8
    term: "Comprehension"
  - id: 9
    term: "Computer-assisted language learning"
  - id: 10
    term: "Conversation"
  - id: 11
    term: "Cross-linguistic influence"
  - id: 12
    term: "Cultural identity"
  - id: 13
    term: "Culture"
  - id: 14
    term: "Discourse"
  - id: 15
    term: "Effectiveness of teaching"
  - id: 16
    term: "Error correction / Corrective feedback"
  - id: 17
    term: "Figurative language (metaphor)"
  - id: 18
    term: "Fluency"
  - id: 19
    term: "Grammar"
  - id: 20
    term: "Identity"
  - id: 21
    term: "Implicit learning"
  - id: 23
    term: "Interaction"
  - id: 24
    term: "Learner attitudes"
  - id: 25
    term: "Learner silence"
  - id: 26
    term: "Learner strategies"
  - id: 28
    term: "Learning"
  - id: 27
    term: "Learning style"
  - id: 29
    term: "Linguistic identity"
  - id: 55
    term: "Listening"
  - id: 30
    term: "Meta-analysis"
  - id: 31
    term: "Motivation"
  - id: 32
    term: "Multilingualism"
  - id: 33
    term: "Native / Non-native"
  - id: 34
    term: "Phonology"
  - id: 35
    term: "Pragmatic competence"
  - id: 36
    term: "Processing"
  - id: 37
    term: "Production"
  - id: 38
    term: "Proficiency"
  - id: 39
    term: "Pronunciation"
  - id: 40
    term: "Prosody"
  - id: 56
    term: "Reading"
  - id: 41
    term: "Research methods"
  - id: 42
    term: "Self-efficacy"
  - id: 43
    term: "Sentence processing"
  - id: 57
    term: "Speaking"
  - id: 44
    term: "Study abroad"
  - id: 45
    term: "Tasks"
  - id: 46
    term: "Teacher cognition"
  - id: 47
    term: "Teacher education"
  - id: 59
    term: "Teaching Methods: Communicative Language Teaching"
  - id: 60
    term: "Teaching Methods: Content and Language Integrated Learning (CLIL)"
  - id: 58
    term: "Teaching Methods: Immersion"
  - id: 61
    term: "Teaching Methods: Processing Instruction"
  - id: 63
    term: "Teaching Methods: Task repetition"
  - id: 62
    term: "Teaching Methods: Task-Based Language Teaching (TBLT)"
  - id: 48
    term: "Teaching materials and curriculum (syllabus, textbook design)"
  - id: 49
    term: "Teaching methods (style, approach, technique)"
  - id: 50
    term: "Teaching policy"
  - id: 51
    term: "Testing"
  - id: 52
    term: "Vocabulary"
  - id: 64
    term: "Willingness to communicate"
  - id: 53
    term: "Working memory"
  - id: 65
    term: "Writing"
  - id: 54
    term: "Other"
