# This is a sample config file that points to a solr server for each environment
development:
  url: <%= Figaro.env.solr_url %>
test:
  url: <%= Figaro.env.solr_url %>
production:
  url: <%= Figaro.env.solr_url %>
